services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - ./data/mongodb_data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "12379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"] # Enable AOF persistence

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: workout-app
    restart: always
    ports:
      - "1221:1221"
    env_file: 
      - .env
    environment:
      PORT: 1221
      SECRET_KEY: ${SECRET_KEY}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_URI: ${MONGO_URI}
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - mongodb
      - redis          # app starts last
    volumes:
      - .:/usr/src/app # Mount local files for development purposes
      - ./data/exports:/exports

volumes:
  mongodb_data:
  redis_data:
