services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017" # Expose MongoDB on the default port
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - ./data/mongodb_data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: workout-app
    restart: always
    ports:
      - "1221:1221"
    environment:
      PORT: 1221
      SECRET_KEY: ${SECRET_KEY}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_URI: ${MONGO_URI}
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app # Mount local files for development purposes

volumes:
  mongodb_data:
