services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    ulimits:
      nofile:
        soft: 64000
        hard: 64000
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      GLIBC_TUNABLES: glibc.pthread.rseq=0        # tcmalloc does not fully support rseq (help)
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "12379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"] # Enable AOF persistence

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: workout-app
    restart: always
    ports:
      - "1221:1221"
    env_file: 
      - .env
      - settings.env
    environment:
      PORT: 1221
      SECRET_KEY: ${SECRET_KEY}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_URI: ${MONGO_URI}
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - mongodb
      - redis          # app starts last
    volumes:
      - app_data:/data
      - app_exports:/exports

  admin-portal:
    build:
      context: ../admin-portal
      dockerfile: Dockerfile
      args:
          REACT_APP_API_BASE_URL: ${REACT_APP_API_BASE_URL}
    env_file:
      - ../admin-portal/.env
    environment:
      - REACT_APP_API_BASE_URL=https://test.ion606.com
    ports:
      - "1122:80"
    restart: always

volumes:
  mongodb_data:
  redis_data:
  app_data:
  app_exports:
